### PR TITLE
Created the Day planner page

### LINKED ISSUE #26: Create a Day planner
Recommend activities to do according to the weather. The day planner takes up a separate page consisting of :

- cards that display activities ( clickable) 
- display the current weather
- A block that displays the list of activities on selection

### PR DESCRIPTION
**Pull request by suppixie**
The day planner page suggests activities to do based on the location and weather. It also allows you to make a todo list by selecting the activities.

Fixes #26 

image

### CODE REVIEW

**Comment by suppixie** [comment]
@akshgpt7 please check, I have fixed the merge conflicts.

**Comment by akshgpt7** [comment]
Looks beautiful!
It just keeps loading for me though:
image

Does it need any API keys added to netlify?

**Comment by suppixie** [comment]
Hey @akshgpt7 , yes it needs an openAI api key, Akansha had already informed earlier but i guess it wasnt added.

**Comment by akshgpt7** [comment]
I have added the API key to netlify, and rest of it looks great. Thanks for working on this!

**Pull request merged**
