### PR TITLE
Graphs and cards for climate change page 

### PR DESCRIPTION
**Pull request by k-abirami**
image
image

closes issues #18 and #21

### CODE REVIEW

**Comment by akshgpt7** [comment]
The Air quality graph isn't showing for me, can you checkk it?
image

Rest looks pretty great!

**Comment by kristinlam** [comment]
@akshgpt7 I added error handling to the climate change page for geocoded searches and air pollution searches.

I also fixed an error caused by two duplicate useEffect hooks in App.js in the main repo, which is preventing our forecast from being fetched on the deployed site.

**Comment by akshgpt7** [comment]
LGTM!
Let me know if any API keys need to be added to netlify.

**Comment by kristinlam** [comment]
@akshgpt7, thank you for checking this. No API keys have to be added — the historical data is from a free, public API and the air quality one is from OpenWeatherMap.

**Pull request merged**
