### PR TITLE
Flight api 2

### LINKED ISSUE #14: Add Flight API
Add a flight prices API to show users the flight prices of their trip wrt. dates and source+destination

### PR DESCRIPTION
**Pull request by jaygala223**
Added code for a newer flight API that uses Skyscanner. Also, fixed routing and UI.

The netlify website will probably need a key that can be generated for free from here: https://rapidapi.com/3b-data-3b-data-default/api/skyscanner44/

Fixes #14

### CODE REVIEW

**Comment by akshgpt7** [comment]
@jaygala223 is this ready for review?

**Comment by jaygala223** [comment]
Yes @akshgpt7 it is ready to be reviewed

Edit: Sorry, need to fix the UI before merging. I am working on it now and will tag you for review once done

**Comment by jaygala223** [comment]
This is what it will look like once the flight API key has been added

image

**Comment by ttn-ttn** [comment]
@jaygala223 are you going to use this API for sure? If so, I will add it to the proxy so it doesn't leak the keys.

By the way, this API seems to be capped at 100 requests per month.

**Comment by jaygala223** [comment]
Yes, I think we'll go ahead with this API for now. It's the best I could find

**Pull request merged**
